### PR TITLE
Port commits since the fork to the sass file

### PR DESCRIPTION
**Pull request by germanfr**
Some things were fixed only in the default variant and now are in the three ones.

### CODE REVIEW

**Comment by oberon-manjaro** [comment]
Right. now to get rid of the conflicts I guess I will need to revert all the original changes in my fork, right?
What I still don't understand is, since css files get created automatically from sass, why is it we have these css files at all, especially if they contain outdated styling?

**Comment by oberon-manjaro** [comment]
Ah. I see now. I should have merged this before the cinnamon-header PR ... That's all. :wink:

**Comment by germanfr** [comment]
Don't worry, I'll rebase

**Comment by germanfr** [comment]
> What I still don't understand is, since css files get created automatically from sass, why is it we have these css files at all, especially if they contain outdated styling?

Because scss files are not understood by gtk. It is good to have css and sass paired. In this case the outdated was sass.

**Comment by germanfr** [comment]
There are no conflicts now @oberon2007

**Comment by oberon-manjaro** [comment]
awesome, thanks!

**Pull request merged**
